name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test 
    - name: Run sbt docker Finatra-docker-example
      run: cd Finatra-docker-example && sbt docker:publishLocal
    - name: Run sbt docker BasicExample
      run: cd BasicExample && sbt docker:publishLocal
    - name: Run sbt docker akkahttp-docker-example
      run: cd akkahttp-docker-example && sbt docker:publishLocal
    - name: Check results
      run: docker ps -a  && docker images
    - name: Build playTODO
      run: cd playTODO && sbt test && sbt assembly
      
